#!/usr/bin/python
import os
import subprocess
import argparse
import sys
import json
import re
import fnmatch

def dump_json(data):
    print json.dumps(data)
    sys.exit(0)

def nd_trigger():
    command = "/infoblox/one/bin/ndc_trigger"

    ret = subprocess.Popen(command,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                shell=True)

# nd_cleanup cleans up the status file which is stored in /storage/heka location
def nd_cleanup():
    stat_dir = "/storage/heka/"

    try:
        regex = re.compile(r'^hotfix_')
        for root, dirs, files in os.walk(stat_dir):
            if root == stat_dir:
                for file in files:
                    if regex.search(file):
                        command = "rm " + stat_dir + file
                        os.system(command)
    except Exception as e:
        dump_json({'code':1,'message':str(e)})

if __name__ == "__main__":

    try:
        my_parser = argparse.ArgumentParser()
        my_parser.add_argument('--trigger', action='store_true', help='Collects stat files from members')
        my_parser.add_argument('--cleanup', action='store_true', help='Cleanup stat files')

        args = my_parser.parse_args()

        if args.trigger:
           nd_trigger()
        elif args.cleanup:
           nd_cleanup()
        # Return code 0 on success
        dump_json({'code':0,'message':''})
    except Exception as e:
        # Return code 1 on failure
        dump_json({'code':1,'message':str(e)})
